KAKAO:
  CLIENT_ID: 4c2e4d4852cafb55e5d18db0521ecee3
  CLIENT_SECRET: NkzavTQYRPwGRFgbWHTtLxc7Zsr2Ncuf

jwt:
  secret: dnflwlqrnlduqenddlrlackehfsjansjanrnldudnj

FRONT_URL: http://localhost:3000
#BACK_URL: http://3.36.123.194:8081
BACK_URL: http://localhost:8081

DATABASE_NAME: mst
ROOT_PASSWORD: mst@0117