# kakao oauth2 설정
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO.CLIENT_ID}
            redirect-uri: ${BACK_URL}/login/oauth2/code/kakao # http://localhost:8081/login/oauth2/code/kakao
            #            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            #            redirect-uri: {baseUrl}/login/oauth2/code/{registrationId} # http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            client-secret: ${KAKAO.CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#jwt:
#  token:
#    secret-key: chadoll
#  access-token:
#    expire-length: 1800000
#  refresh-token:
#    expire-length: 1209600000