KAKAO:
  CLIENT_ID: 4c2e4d4852cafb55e5d18db0521ecee3
  CLIENT_SECRET: NkzavTQYRPwGRFgbWHTtLxc7Zsr2Ncuf

FRONT_URL: http://localhost:3000
BACK_URL: http://3.39.97.18:8081
#BACK_URL: http://localhost:8081
#DOMAIN: masyeotta.site
#HOST_IP: 3.39.97.18

EUREKA:
#  IP: localhost
  IP: 3.39.97.18
  USERNAME: admin
  PASSWORD: mst0117

DATABASE:
  DATASOURCE:
    URL: jdbc:mysql://3.39.97.18:3306/mst?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    USERNAME: admin
    PASSWORD: mst@0117

JWT:
  TOKEN:
    SECRET-KEY: dnflwlqrnlduqenddlrlackehfsjansjanrnldudnj
  ACCESS-TOKEN:
    # 1시간
    EXPIRE-LENGTH: 3600000
    # 10분
    # EXPIRE-LENGTH: 600000
  REFRESH-TOKEN:
    # 24시간
    EXPIRE-LENGTH: 86400000