server:
  port: 8083

spring:
  application:
    name: community-service

# 유레카 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234mst@localhost:8761/eureka
