server:
#  port: 0
  port: 8083

spring:
  application:
    name: community-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: ${SPRING_DATASOURCE_URL}
    url: jdbc:mysql://localhost:3306/MST?useSSL=false&serverTimezone=UTC
    username: admin
    #    password: ${SPRING_DATASOURCE_PASSWORD}
    password: mst@0117
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    # 데이터베이스 스키마를 자동으로 업데이트할지 여부 (db 초기화 전략. create: 기존 테이블 삭제 후 생성)
    hibernate:
      ddl-auto: update
    # SQL 쿼리를 로그로 출력할지 여부
    show-sql: true
    # SQL 쿼리를 출력할 때 가독성을 높이기 위해 서식을 지정
    properties:
      hibernate:
        format_sql: true

# 유레카 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234mst@localhost:8761/eureka

greeting:
  message: Welcome to the MST Project.
