server:
  port: 8083

spring:
  application:
    name: community-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.123.194:3308/mst?useSSL=false&serverTimezone=UTC
    username: admin
    password: mst@0117
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    # 데이터베이스 스키마를 자동 업데이트 설정
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 유레카 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234mst@3.36.123.194:8761/eureka

greeting:
  message: Welcome to the MST Project.
