server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
        - id: beverage-service
          uri: http://localhost:8082
          predicates:
            - Path=/beverage-service/**
        - id: community-service
          uri: http://localhost:8083
          predicates:
            - path=/community-service/**
