server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: beverage-service
          uri: http://localhost:8082
          predicates:
            - Path=/beverage-service/**
          filters:
            - RewritePath=/beverage-service/(?<segment>.*),/$\{segment}
        - id: community-service
          uri: http://localhost:8083
          predicates:
            - Path=/community-service/**
          filters:
            - RewritePath=/community-service/(?<segment>.*),/$\{segment}